# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

exclude: ["README.md", "LICENCE", "workshops.Rproj"]
highlighter: rouge

title: workshops
author:
  name: Ivan Hanigan
  email: ivan.hanigan@curtin.edu.au
  github: ivanhanigan

# this is just too confusing
  # kbroman says
  # A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  # REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH

baseurl: /workshops
